main/blog/urls.py
from django.urls import path

from blog.views import BlogPostDetailView, BlogListView
from shop import views



urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/<slug:slug>', BlogPostDetailView.as_view(), name='blog_detail'),
]

main/cart/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

main/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from shop import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('shop.urls')),
                  path('cart/', include('cart.urls')),
                  path('', include('authentication.urls')),
                  path('', include('blog.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'shop.views.customhandler404'

main/shop/urls.py
from django.urls import path

from shop import views



urlpatterns = [
    path('', views.index, name='home'),
    path('product/<slug:brand_slug>/', views.ProductListView.as_view(), name='shop_brand'),
    path('product/<slug:brand_slug>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

main/blog/models.py
from django.db import models
from django.urls import reverse

from main import settings


class BlogPost(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Автор')
    title = models.CharField(max_length=300, default=None)
    image = models.ImageField(help_text='830x390', upload_to='BlogImages')
    data_publish = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=400, unique=True, db_index=True, verbose_name="URL", default=None)
    descr = models.CharField(max_length=1000, null=True, blank=True, default=None)
    author_desc = models.CharField(max_length=500, null=True, blank=True, default=None)

    class Meta:
        verbose_name = ('Пост')
        verbose_name_plural = ('Посты блога')

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def __str__(self):
        return self.title

main/shop/models.py
from django.db import models
from django.urls import reverse

from main import settings


class Brand(models.Model):
    brand_name = models.CharField(max_length=200,verbose_name='Бренд')
    Androind = models.BooleanField(default=None, verbose_name='Андроид')
    slug = models.SlugField(max_length=400, unique=True, db_index=True, verbose_name="URL", default=None)
    brand_logo = models.ImageField(upload_to='brand_logos', help_text='270x300', default='default',verbose_name='Лого Бренда')



    def __str__(self):
        return self.brand_name

    def get_absolute_url(self):
        return reverse('brand', kwargs={'brand_slug':self.slug})

    class Meta:
        verbose_name = ('Бренд')
        verbose_name_plural = ('Бренды')

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя продукта')
    description = models.CharField(max_length=1000, verbose_name='Описание')
    information = models.CharField(max_length=1000, verbose_name='Информация')
    brand = models.ForeignKey(Brand,
                              on_delete=models.CASCADE,
                              related_name='Brand', verbose_name='Бренд')

    rating = models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')
    color = models.CharField(max_length=100, default=None, verbose_name='Цвет')
    slug = models.SlugField(max_length=400, unique=True, db_index=True, verbose_name="URL", default=None)
    price = models.DecimalField(default=0, max_digits=20, decimal_places=2, verbose_name='Цена')

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug':self.slug})

    def __str__(self):
        return '{brand} {name} {color}'.format(
            brand=self.brand,
            name=self.name,
            color=self.color,
        )
    class Meta:
        verbose_name = ('Товар')
        verbose_name_plural = ('Товары')


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery', help_text='270x300')
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='images')
    class Meta:
        verbose_name = ('Фото')
        verbose_name_plural = ('Фотографии')

    def __str__(self):
        return self.product.name


class Reviews(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', null=True,blank=True)
    data_public = models.DateTimeField(verbose_name='Дата отзыва')
    text_review = models.CharField(max_length=255,verbose_name='Отзыв')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Reviews', verbose_name='Товар')

    def __str__(self):
        return '{name} {product}'.format(name=self.user,
                                          product=self.product)

    class Meta:
        verbose_name = ('Отзыв')
        verbose_name_plural = ('Отзывы')


class Ad(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Ads_product', verbose_name='Товар')
    title = models.CharField(max_length=50, verbose_name='Главный текст')
    description = models.CharField(max_length=255, verbose_name='Нижний текст')
    photo = models.ImageField(upload_to='ads', help_text='800x600', verbose_name='Баннер')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = ('Банер')
        verbose_name_plural = ('Рекламные банеры')

main/users/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, Permission
from django.contrib.auth.base_user import AbstractBaseUser

from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    username = None

    COUNTRIES = [
        ('Россия', 'Россия')
    ]

    STATES = [
        ('Краснодарский край', 'Краснодарский край')
    ]

    CITY = [
        ('Краснодар', 'Краснодар')
    ]

    email = models.EmailField(_('Почта'), unique=True)
    first_name = models.CharField(_('Имя'), max_length=30, blank=True)
    last_name = models.CharField(_('Фамилия'), max_length=30, blank=True)
    country = models.CharField(_('Страна'), choices=COUNTRIES,max_length=100, blank=True)
    state = models.CharField(_('Регион'),choices=STATES, max_length=255, blank=True)
    city = models.CharField(_('Город'),choices=CITY,max_length=255, blank=True)

    is_superuser = models.BooleanField(
        _("Суперпользователь"),
        default=False,
        help_text=_(
            "Пользователь имеет все разрешения "
            "без явного их обозначения."
        ),
    )


    last_login = models.DateTimeField(_("Последний вход"), blank=True, null=True)
    date_joined = models.DateTimeField(_('Дата регистрации'), auto_now_add=True)
    is_active = models.BooleanField(_('Аккаунт активирован'), default=True)
    phone = models.CharField(_('Телефон'), max_length=11)
    is_staff = models.BooleanField(
        _("Администратор"),
        default=False,
        help_text=_("Может ли пользователь входить в админку."),
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = ('Пользователь')
        verbose_name_plural = ('Пользователи')


    def __str__(self):
        return self.email
    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def get_last_name(self):
        return self.last_name

    def get_country(self):
        return self.country

    def get_state(self):
        return self.state

    def get_city(self):
        return self.city

    def get_phone(self):
        return self.phone

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

main/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

main/blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic import ListView

from blog.models import BlogPost


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog-details.html'
    context_object_name = 'blog_detail'

class BlogListView(ListView):
    model = BlogPost
    template_name = 'blog.html'
    context_object_name = 'blog_list'

    def get_queryset(self):
        qs = BlogPost.objects.all()
        return qs

main/cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from cart.Cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart})

main/shop/views.py
from django.http import Http404
from django.shortcuts import render

from cart.Cart import Cart
from .models import *
from blog.models import BlogPost
from django.views.generic import DetailView
from django.views.generic import ListView


def index(request):
    ads = Ad.objects.all()
    products = Product.objects.all()
    brands = Brand.objects.all()
    blog_posts = BlogPost.objects.all().order_by('-data_publish')[:3]

    popular_products = Product.objects.all().order_by('-rating')[:10]

    cart = Cart(request)




    context = ({
        'ads': ads,
        'products': products,
        'brands': brands,
        'popular_products': popular_products,
        'posts': blog_posts,
        'cart': cart
    })

    return render(request, 'index.html', context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product-detail.html'
    context_object_name = 'product'
            

class ProductListView(ListView):
    model = Product
    template_name = 'shop-list.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        qs = self.model.objects.all()
        if self.kwargs.get('brand_slug'):
            qs = qs.filter(brand__slug=self.kwargs['brand_slug'])
            check = list(qs)
            if not check:
                raise Http404
        return qs




def customhandler404(request, exception, template_name='404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response

main/templates/login.html
{% extends 'base-page.html' %}
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block title %}
    <title>skyshop || Авторизация</title>
    {% endblock %}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


</head>

<body>


    <!-- Body main wrapper start -->
    <div class="wrapper">
        {% block content %}

        <!-- Start page content -->
        <div id="page-content" class="page-wrapper">

            <!-- LOGIN SECTION START -->
            <div class="login-section mb-80">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="registered-customers">
                                <h6 class="widget-title border-left mb-50">Авторизация</h6>
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="login-account p-30 box-shadow">
                                        <p>Для зарегистрированных пользователей</p>
                                        <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="254" required id="id_username" placeholder="Почта">
                                        <input type="password" name="password" autocomplete="current-password" required id="id_password" placeholder="Пароль">
                                        <p><small><a href="#">Забыли пароль?</a></small></p>
                                        <button class="submit-btn-1 btn-hover-1" type="submit">Вход</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- new-customers -->
                        <div class="col-md-6">
                            <div class="new-customers">

                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <h6 class="widget-title border-left mb-50">Новый пользователь</h6>
                                    <div class="login-account p-30 box-shadow">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <input type="text" name="first_name" maxlength="30" id="id_first_name" placeholder="Имя">
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="text" name="last_name" maxlength="30" id="id_last_name" placeholder="Фамилия">
                                            </div>
                                            <div class="col-sm-6">
                                                <select class="custom-select" name="country" id="id_country">
                                                    <option value="default" selected>Страна</option>
                                                    <option value="Россия">Россия</option>
                                                </select>
                                            </div>
                                            <div class="col-sm-6">
                                                <select class="custom-select" name="State" id="id_state">
                                                    <option value="default" selected>Регион</option>
                                                    <option value="Краснодарский край">Краснодарский край</option>
                                                </select>
                                            </div>
                                            <div class="col-sm-6">
                                                <select class="custom-select" name="city" id="id_city">
                                                    <option value="default" selected>Город</option>
                                                    <option value="Краснодар" id="city_id">Краснодар</option>
                                                </select>
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="text" name="phone" maxlength="11" required id="id_phone"  placeholder="Телефон...">
                                            </div>
                                        </div>
                                        <input type="text" name="email" maxlength="254" autofocus required id="id_email"  placeholder="Email/Почта..">
                                        <input type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="Пароль">
                                        <input type="password" name="password2" autocomplete="new-password" required id="id_password2" placeholder="Повторите пароль">
                                        <div class="checkbox">
                                            <label class="mr-10"> 
                                                <small>
                                                    <input type="checkbox" name="Регистрация">Подписаться на нашу рассылку!
                                                </small>
                                            </label>
                                            <label> 
                                                <small>
                                                    <input type="checkbox" name="signup">Подписаться на рассылку от наших партнеров!
                                                </small>
                                            </label>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <button class="submit-btn-1 mt-20 btn-hover-1" type="submit" value="">Регистрация</button>
                                            </div>
                                            <div class="col-md-6">
                                                <button class="submit-btn-1 mt-20 btn-hover-1 f-right" type="reset">Очистить поля</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- LOGIN SECTION END -->             

        </div>
        <!-- End page content -->

        {% endblock %}
    </div>
    <!-- Body main wrapper end -->


</body>

</html>